In [1]:
import torch

In [2]:
torch.empty(1)

tensor([0.])

In [3]:
torch.empty(3)

tensor([ 8.4078e-45,  0.0000e+00, -2.7147e+00])

In [4]:
torch.empty(2,3)

tensor([[ 0.0000e+00, -1.5846e+29,  2.3715e-11],
        [-2.5250e-29,  8.4078e-45,  0.0000e+00]])

In [5]:
torch.zeros(2,3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [6]:
torch.ones(2,3,3)

tensor([[[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]]])

In [8]:
tensor1 = torch.ones(2, 3)
tensor1.type()

'torch.FloatTensor'

In [10]:
tensor1 = torch.ones(2, 3, dtype=torch.float32)
tensor1.type()

'torch.FloatTensor'

In [11]:
tensor1 = torch.ones(2, 3, dtype=torch.float64)
tensor1.type()

'torch.DoubleTensor'