In [1]:
import torch

# 初始化一个Tensor

In [2]:
torch.empty(1)

tensor([0.])

In [3]:
torch.empty(3)

tensor([ 8.4078e-45,  0.0000e+00, -2.7147e+00])

In [4]:
torch.empty(2,3)

tensor([[ 0.0000e+00, -1.5846e+29,  2.3715e-11],
        [-2.5250e-29,  8.4078e-45,  0.0000e+00]])

In [5]:
torch.zeros(2,3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [6]:
torch.ones(2,3,3)

tensor([[[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]]])

# 改变Tensor的属性

In [8]:
tensor1 = torch.ones(2, 3)
tensor1.type()

'torch.FloatTensor'

In [10]:
tensor1 = torch.ones(2, 3, dtype=torch.float32)
tensor1.type()

'torch.FloatTensor'

In [11]:
tensor1 = torch.ones(2, 3, dtype=torch.float64)
tensor1.type()

'torch.DoubleTensor'

In [12]:
tensor1.size()

torch.Size([2, 3])

# Tensor加减乘除法

In [13]:
x = torch.rand(2,2)
y = torch.rand(2,2)
print(x)
print(y)
print(f'x+y = {x+y}')
print(f'x+y = {torch.add(x, y)}')
# y.add_(x) 这行代码等价于y = y-x

tensor([[0.8985, 0.3175],
        [0.0958, 0.2810]])
tensor([[0.1718, 0.1470],
        [0.6138, 0.8397]])
x+y = tensor([[1.0703, 0.4645],
        [0.7096, 1.1207]])
x+y = tensor([[1.0703, 0.4645],
        [0.7096, 1.1207]])


In [14]:
print(f'x-y = {x-y}')
print(f'x-y = {torch.sub(x, y)}')
# y.sub_(x) 这行代码等价于y = y-x

x-y = tensor([[ 0.7268,  0.1705],
        [-0.5181, -0.5586]])
x-y = tensor([[ 0.7268,  0.1705],
        [-0.5181, -0.5586]])


In [15]:
print(f'x*y = {x*y}')
print(f'x*y = {torch.mul(x, y)}')
# y.mul_(x) 这行代码等价于y = y-x

x*y = tensor([[0.1543, 0.0467],
        [0.0588, 0.2360]])
x*y = tensor([[0.1543, 0.0467],
        [0.0588, 0.2360]])


In [16]:
print(f'x/y = {x/y}')
print(f'x/y = {torch.div(x, y)}')
# y.div_(x) 这行代码等价于y = y/x

x/y = tensor([[5.2312, 2.1593],
        [0.1560, 0.3347]])
x/y = tensor([[5.2312, 2.1593],
        [0.1560, 0.3347]])


# Tensor的切片 (用法和方式与numpy一致)

In [20]:
x = torch.rand(5,3)
print(x)
print(x[3,:])
print(x[2:3,1:2])

tensor([[0.0951, 0.7759, 0.4182],
        [0.4525, 0.1449, 0.5564],
        [0.6265, 0.5619, 0.9139],
        [0.9351, 0.1972, 0.2434],
        [0.9775, 0.8527, 0.9411]])
tensor([0.9351, 0.1972, 0.2434])
tensor([[0.5619]])


# Tensor Reshape

In [21]:
x = torch.rand(5, 4)
print(x.reshape(4, 5))
print(x.view(2,10))

tensor([[0.9649, 0.1717, 0.0428, 0.1783, 0.0404],
        [0.3371, 0.1543, 0.6023, 0.6847, 0.1689],
        [0.2616, 0.9281, 0.3148, 0.4253, 0.3364],
        [0.0457, 0.8371, 0.0050, 0.2101, 0.0773]])
tensor([[0.9649, 0.1717, 0.0428, 0.1783, 0.0404, 0.3371, 0.1543, 0.6023, 0.6847,
         0.1689],
        [0.2616, 0.9281, 0.3148, 0.4253, 0.3364, 0.0457, 0.8371, 0.0050, 0.2101,
         0.0773]])


# Tensor和Numpy转换

In [25]:
x = torch.ones(5)
print(x)
y = x.numpy()
print(y)

tensor([1., 1., 1., 1., 1.])
[1. 1. 1. 1. 1.]


In [16]:
# 注意事项： 如果你在GPU上面创建了一个Tensor数据类型，将Tensor转化为Numpy格式的话，是会报错的，因为Numpy只能在CPU上面进行转化。

# 关于创建Tensor 优化模型的重要事项

In [16]:
x = torch.ones(5, requires_grad=True)
# 很多时候，我们看到一个Tensor标注了requires_grad=True的意思就是
# 告诉Pytorch这个变量之后还会在模型的优化计算中用到，所以需要设置